version: '3.8'

services:
  # Naš Message Broker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Naša Vektorska Baza
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"

  # Naš API Gateway
  gateway-api:
    container_name: gateway-api
    build:
      context: .
      dockerfile: Gateway.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      rabbitmq:
        condition: service_healthy

  # Naš AI Worker
  ai-worker:
    container_name: ai-worker
    build:
      context: .
      dockerfile: AI.Worker/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      rabbitmq:
        condition: service_healthy
      qdrant:
        condition: service_started